// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Message.proto

package com.infogen.grpc;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.infogen.grpc.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 sequence = 1;</code>
     */
    long getSequence();

    /**
     * <code>optional string method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>map&lt;string, string&gt; parameters = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getParameters();
  }
  /**
   * Protobuf type {@code com.infogen.grpc.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.infogen.grpc.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Request() {
      sequence_ = 0L;
      method_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sequence_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              method_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                parameters_ = com.google.protobuf.MapField.newMapField(
                    parametersDefaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              parameters = input.readMessage(
                  parametersDefaultEntry.getParserForType(), extensionRegistry);
              parameters_.getMutableMap().put(parameters.getKey(), parameters.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Request_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return parameters_;
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.infogen.grpc.MessageOuterClass.Request.class, com.infogen.grpc.MessageOuterClass.Request.Builder.class);
    }

    public static final com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SEQUENCE_FIELD_NUMBER = 1;
    private long sequence_;
    /**
     * <code>optional int64 sequence = 1;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private java.lang.Object method_;
    /**
     * <code>optional string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 3;
    private static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> parametersDefaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Request_ParametersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> parameters_ =
            com.google.protobuf.MapField.emptyMapField(
                parametersDefaultEntry);

    /**
     * <code>map&lt;string, string&gt; parameters = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getParameters() {
      return parameters_.getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (sequence_ != 0L) {
        output.writeInt64(1, sequence_);
      }
      if (!getMethodBytes().isEmpty()) {
        output.writeBytes(2, getMethodBytes());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : parameters_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        parameters = parametersDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, parameters);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sequence_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodBytes());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : parameters_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        parameters = parametersDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, parameters);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.infogen.grpc.MessageOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.infogen.grpc.MessageOuterClass.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.infogen.grpc.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.infogen.grpc.Request)
        com.infogen.grpc.MessageOuterClass.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Request_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return parameters_;
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.infogen.grpc.MessageOuterClass.Request.class, com.infogen.grpc.MessageOuterClass.Request.Builder.class);
      }

      // Construct using com.infogen.grpc.MessageOuterClass.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sequence_ = 0L;

        method_ = "";

        parameters_.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Request_descriptor;
      }

      public com.infogen.grpc.MessageOuterClass.Request getDefaultInstanceForType() {
        return com.infogen.grpc.MessageOuterClass.Request.getDefaultInstance();
      }

      public com.infogen.grpc.MessageOuterClass.Request build() {
        com.infogen.grpc.MessageOuterClass.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.infogen.grpc.MessageOuterClass.Request buildPartial() {
        com.infogen.grpc.MessageOuterClass.Request result = new com.infogen.grpc.MessageOuterClass.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.sequence_ = sequence_;
        result.method_ = method_;
        result.parameters_ = parameters_.copy();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.infogen.grpc.MessageOuterClass.Request) {
          return mergeFrom((com.infogen.grpc.MessageOuterClass.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.infogen.grpc.MessageOuterClass.Request other) {
        if (other == com.infogen.grpc.MessageOuterClass.Request.getDefaultInstance()) return this;
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        parameters_.mergeFrom(other.parameters_);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.infogen.grpc.MessageOuterClass.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.infogen.grpc.MessageOuterClass.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long sequence_ ;
      /**
       * <code>optional int64 sequence = 1;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional int64 sequence = 1;</code>
       */
      public Builder setSequence(long value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sequence = 1;</code>
       */
      public Builder clearSequence() {
        
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            method_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> parameters_ =
              com.google.protobuf.MapField.newMapField(
                  parametersDefaultEntry);

      /**
       * <code>map&lt;string, string&gt; parameters = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getParameters() {
        return parameters_.getMap();
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableParameters() {
        onChanged();
        return parameters_.getMutableMap();
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.infogen.grpc.Request)
    }

    // @@protoc_insertion_point(class_scope:com.infogen.grpc.Request)
    private static final com.infogen.grpc.MessageOuterClass.Request defaultInstance;static {
      defaultInstance = new com.infogen.grpc.MessageOuterClass.Request();
    }

    public static com.infogen.grpc.MessageOuterClass.Request getDefaultInstance() {
      return defaultInstance;
    }

    public com.infogen.grpc.MessageOuterClass.Request getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.infogen.grpc.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 sequence = 1;</code>
     */
    long getSequence();

    /**
     * <code>optional string method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>optional string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>optional bool success = 4;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional int32 code = 5;</code>
     */
    int getCode();

    /**
     * <code>optional string note = 6;</code>
     */
    java.lang.String getNote();
    /**
     * <code>optional string note = 6;</code>
     */
    com.google.protobuf.ByteString
        getNoteBytes();
  }
  /**
   * Protobuf type {@code com.infogen.grpc.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.infogen.grpc.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Response() {
      sequence_ = 0L;
      method_ = "";
      data_ = "";
      success_ = false;
      code_ = 0;
      note_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sequence_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              method_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();

              data_ = bs;
              break;
            }
            case 32: {

              success_ = input.readBool();
              break;
            }
            case 40: {

              code_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();

              note_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.infogen.grpc.MessageOuterClass.Response.class, com.infogen.grpc.MessageOuterClass.Response.Builder.class);
    }

    public static final com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 1;
    private long sequence_;
    /**
     * <code>optional int64 sequence = 1;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private java.lang.Object method_;
    /**
     * <code>optional string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESS_FIELD_NUMBER = 4;
    private boolean success_;
    /**
     * <code>optional bool success = 4;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int CODE_FIELD_NUMBER = 5;
    private int code_;
    /**
     * <code>optional int32 code = 5;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int NOTE_FIELD_NUMBER = 6;
    private java.lang.Object note_;
    /**
     * <code>optional string note = 6;</code>
     */
    public java.lang.String getNote() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          note_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string note = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (sequence_ != 0L) {
        output.writeInt64(1, sequence_);
      }
      if (!getMethodBytes().isEmpty()) {
        output.writeBytes(2, getMethodBytes());
      }
      if (!getDataBytes().isEmpty()) {
        output.writeBytes(3, getDataBytes());
      }
      if (success_ != false) {
        output.writeBool(4, success_);
      }
      if (code_ != 0) {
        output.writeInt32(5, code_);
      }
      if (!getNoteBytes().isEmpty()) {
        output.writeBytes(6, getNoteBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sequence_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodBytes());
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataBytes());
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, success_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, code_);
      }
      if (!getNoteBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getNoteBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.infogen.grpc.MessageOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.infogen.grpc.MessageOuterClass.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.infogen.grpc.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.infogen.grpc.Response)
        com.infogen.grpc.MessageOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.infogen.grpc.MessageOuterClass.Response.class, com.infogen.grpc.MessageOuterClass.Response.Builder.class);
      }

      // Construct using com.infogen.grpc.MessageOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sequence_ = 0L;

        method_ = "";

        data_ = "";

        success_ = false;

        code_ = 0;

        note_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.infogen.grpc.MessageOuterClass.internal_static_com_infogen_grpc_Response_descriptor;
      }

      public com.infogen.grpc.MessageOuterClass.Response getDefaultInstanceForType() {
        return com.infogen.grpc.MessageOuterClass.Response.getDefaultInstance();
      }

      public com.infogen.grpc.MessageOuterClass.Response build() {
        com.infogen.grpc.MessageOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.infogen.grpc.MessageOuterClass.Response buildPartial() {
        com.infogen.grpc.MessageOuterClass.Response result = new com.infogen.grpc.MessageOuterClass.Response(this);
        result.sequence_ = sequence_;
        result.method_ = method_;
        result.data_ = data_;
        result.success_ = success_;
        result.code_ = code_;
        result.note_ = note_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.infogen.grpc.MessageOuterClass.Response) {
          return mergeFrom((com.infogen.grpc.MessageOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.infogen.grpc.MessageOuterClass.Response other) {
        if (other == com.infogen.grpc.MessageOuterClass.Response.getDefaultInstance()) return this;
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getNote().isEmpty()) {
          note_ = other.note_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.infogen.grpc.MessageOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.infogen.grpc.MessageOuterClass.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sequence_ ;
      /**
       * <code>optional int64 sequence = 1;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional int64 sequence = 1;</code>
       */
      public Builder setSequence(long value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sequence = 1;</code>
       */
      public Builder clearSequence() {
        
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            method_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>optional bool success = 4;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 4;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 4;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 5;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 5;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 5;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object note_ = "";
      /**
       * <code>optional string note = 6;</code>
       */
      public java.lang.String getNote() {
        java.lang.Object ref = note_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            note_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string note = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNoteBytes() {
        java.lang.Object ref = note_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          note_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string note = 6;</code>
       */
      public Builder setNote(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        note_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string note = 6;</code>
       */
      public Builder clearNote() {
        
        note_ = getDefaultInstance().getNote();
        onChanged();
        return this;
      }
      /**
       * <code>optional string note = 6;</code>
       */
      public Builder setNoteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        note_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.infogen.grpc.Response)
    }

    // @@protoc_insertion_point(class_scope:com.infogen.grpc.Response)
    private static final com.infogen.grpc.MessageOuterClass.Response defaultInstance;static {
      defaultInstance = new com.infogen.grpc.MessageOuterClass.Response();
    }

    public static com.infogen.grpc.MessageOuterClass.Response getDefaultInstance() {
      return defaultInstance;
    }

    public com.infogen.grpc.MessageOuterClass.Response getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_infogen_grpc_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_infogen_grpc_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_infogen_grpc_Request_ParametersEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_infogen_grpc_Request_ParametersEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_infogen_grpc_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_infogen_grpc_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protobuf/Message.proto\022\020com.infogen.gr" +
      "pc\"\235\001\n\007Request\022\020\n\010sequence\030\001 \001(\003\022\016\n\006meth" +
      "od\030\002 \001(\t\022=\n\nparameters\030\003 \003(\0132).com.infog" +
      "en.grpc.Request.ParametersEntry\0321\n\017Param" +
      "etersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001\"g\n\010Response\022\020\n\010sequence\030\001 \001(\003\022\016\n\006meth" +
      "od\030\002 \001(\t\022\014\n\004data\030\003 \001(\t\022\017\n\007success\030\004 \001(\010\022" +
      "\014\n\004code\030\005 \001(\005\022\014\n\004note\030\006 \001(\t2J\n\007Message\022?" +
      "\n\004call\022\031.com.infogen.grpc.Request\032\032.com." +
      "infogen.grpc.Response\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_infogen_grpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_infogen_grpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_infogen_grpc_Request_descriptor,
        new java.lang.String[] { "Sequence", "Method", "Parameters", });
    internal_static_com_infogen_grpc_Request_ParametersEntry_descriptor =
      internal_static_com_infogen_grpc_Request_descriptor.getNestedTypes().get(0);
    internal_static_com_infogen_grpc_Request_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_infogen_grpc_Request_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_infogen_grpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_infogen_grpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_infogen_grpc_Response_descriptor,
        new java.lang.String[] { "Sequence", "Method", "Data", "Success", "Code", "Note", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
