// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.infogen.infogen_demo.protoc;

public interface HttpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HttpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string note = 1;</code>
   */
  java.lang.String getNote();
  /**
   * <code>optional string note = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoteBytes();
}
