// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.infogen.infogen_demo.protoc;

public final class Message {
	private Message() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	static com.google.protobuf.Descriptors.Descriptor internal_static_HttpRequest_descriptor;
	static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_HttpRequest_fieldAccessorTable;
	static com.google.protobuf.Descriptors.Descriptor internal_static_HttpResponse_descriptor;
	static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_HttpResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

	static {
		java.lang.String[] descriptorData = { "\n\rMessage.proto\"\033\n\013HttpRequest\022\014\n\004note\030\001" + " \001(\t\"\034\n\014HttpResponse\022\014\n\004note\030\001 \001(\t24\n\016Me" + "ssageService\022\"\n\003get\022\014.HttpRequest\032\r.Http" + "ResponseB4\n$com.infogen.infogen_demo.htt" + "p.protocB\007MessageP\001\210\001\001b\006proto3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_HttpRequest_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_HttpRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_HttpRequest_descriptor, new java.lang.String[] { "Note", });
		internal_static_HttpResponse_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_HttpResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_HttpResponse_descriptor, new java.lang.String[] { "Note", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
